version: 2.1

jobs:
  run-java-tests:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Run Java Unit Tests
          command: |
            mkdir -p test-results
            TESTFILES=$(circleci tests glob "src/test/java/**/*.java")
            echo "$TESTFILES" | circleci tests run --command="xargs javac" --split-by=timings
      - store_test_results:
          path: test-results

workflows:
  test-workflow:
    jobs:
      - run-java-tests